spring.application.name=agencia

jwt.secret=${JWT_SECRET:troque-esta-chave-para-algo-secreto-com-mais-de-32-caracteres}

jwt.expiration-ms=900000

jwt.internal-expiration-ms=60000

logging.level.org.springframework.security=WARN

spring.rabbitmq.addresses=${RABBITMQ_URL}
